// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	wrapper "github.com/ppussar/mongodb_exporter/internal/wrapper"
	mock "github.com/stretchr/testify/mock"
)

// IConnection is an autogenerated mock type for the IConnection type
type IConnection struct {
	mock.Mock
}

// Aggregate provides a mock function with given fields: db, collection, command, ctx
func (_m *IConnection) Aggregate(db string, collection string, command string, ctx context.Context) (wrapper.ICursor, error) {
	ret := _m.Called(db, collection, command, ctx)

	var r0 wrapper.ICursor
	if rf, ok := ret.Get(0).(func(string, string, string, context.Context) wrapper.ICursor); ok {
		r0 = rf(db, collection, command, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.ICursor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, context.Context) error); ok {
		r1 = rf(db, collection, command, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: db, collection, command, ctx
func (_m *IConnection) Find(db string, collection string, command string, ctx context.Context) (wrapper.ICursor, error) {
	ret := _m.Called(db, collection, command, ctx)

	var r0 wrapper.ICursor
	if rf, ok := ret.Get(0).(func(string, string, string, context.Context) wrapper.ICursor); ok {
		r0 = rf(db, collection, command, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.ICursor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, context.Context) error); ok {
		r1 = rf(db, collection, command, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
