---
language: go

services:
  - 'docker'

go:
  - 1.13.x

git:
  depth: 1

env:
  - GO111MODULE=on

script:
  - make build
  #- make test
  - make image

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi