# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
  push_image:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      - run: make image
      - run: make push-image

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build
      - push_image:
          requires:
            - build
          filters:
            branches:
              only: master
