---
version: '3.8'
services:
  database:
    image: 'mongo:4.4.18'
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: fruitstore
    volumes:
      - ./fruits.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017-27017:27017-27017"
    restart: always
    healthcheck:
      test: "if mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'; then exit 0; fi; exit 1;"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  exporter:
    build:
      context: ../bin
    container_name: exporter
    environment:
      CONFIG: "/configuration.yaml"
    volumes:
      - ./configuration.yaml:/configuration.yaml
    ports:
      - "9090:9090"
    links:
      - database
    depends_on:
      - database
    restart: always
